- name: user
  hosts: web
  become: yes
  
  tasks:
  - name: user creation
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true
    
  - name: print the user
    ansible.builtin.debug:
      msg: "{{user}}"
  
  - name: creation of user
    ansible.builtin.command: useradd expense
    when: user.rc !=0