- name: variables
  hosts: local
  connection: local
  vars:
    course: "Devops with AWS"
    Duration: 120 Hours
    Trainer: Sivakumar

  tasks:
  - name: print the variables
    ansible.builtin.debug: 
      msg: "Course is {{course}} by {{Trainer}}"
