- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
  - name: Course
    prompt: please enter course name
    name: Duration
    prompt: please enter duration details
    name: Trainer
    prompt: Please enter trainer name
  tasks:
  - name: print course information
    ansible.builtin.debug: 
      msg: "Course is {{Course}} by {{Trainer}}"  